export const demoText = `1. Payment Terms: The Client shall remit payment within 15 days of receipt of the invoice, failing which interest at the rate of 18% per annum may be levied.

2. Confidentiality: Both parties shall keep confidential all proprietary or sensitive information disclosed during the term of this Agreement and for a period of three years thereafter.

3. Termination: Either party may terminate this Agreement by providing 30 days' prior written notice. The Company may terminate immediately in the event of material breach.

4. Auto-Renewal: This Agreement shall automatically renew for successive one-year terms unless either party provides written notice of cancellation at least 45 days before the renewal date.

5. Liability: The Service Provider shall not be liable for any indirect, incidental, or consequential damages arising out of this Agreement.`;

export const learningChallenges = [
  {
    prompt: "A contract says it will renew automatically unless you cancel 45 days before the renewal date. What should you pay attention to most?",
    options: [
      "The cancellation deadline",
      "The color of the document",
      "Only the company name",
    ],
    correctIndex: 0,
    explanation: "Auto-renewal clauses often create hidden risk because people miss the cancellation window.",
  },
  {
    prompt: "A clause says one party can terminate the agreement immediately, but the other party must give 30 days' notice. What is the main issue?",
    options: [
      "The wording may be one-sided",
      "The document is always invalid",
      "The contract must be free",
    ],
    correctIndex: 0,
    explanation: "When one side has much stronger rights than the other, the clause may be unfair or risky.",
  },
  {
    prompt: "A confidentiality clause does not say how long the duty continues. What is the safest response?",
    options: [
      "Ask for the duration to be clearly written",
      "Ignore it because confidentiality is optional",
      "Delete the whole agreement immediately",
    ],
    correctIndex: 0,
    explanation: "A good confidentiality clause should clearly define the information, the allowed disclosures, and the duration.",
  },
];

export const publicDemoReport = {
  title: "Sample Service Agreement",
  overview:
    "This sample agreement has payment, confidentiality, termination, auto-renewal, and liability clauses. The main concerns are renewal timing, liability wording, and contract exit conditions.",
  stats: {
    totalClauses: 5,
    highImportanceClauses: 2,
    riskFlags: 3,
    readingTime: "1 min",
  },
  highlights: [
    "Termination notice period should be checked before signing.",
    "Auto-renewal may create hidden commitment if cancellation is missed.",
    "Liability wording should be reviewed for one-sided financial exposure.",
  ],
  riskyClauses: [
    {
      clauseId: "CL-3",
      title: "Termination",
      simplified:
        "Either side can end the agreement with 30 days' notice, but the company can end it immediately if it says there is a serious breach.",
    },
    {
      clauseId: "CL-4",
      title: "Auto-Renewal",
      simplified:
        "The agreement renews automatically unless someone cancels it at least 45 days before the renewal date.",
    },
    {
      clauseId: "CL-5",
      title: "Liability",
      simplified:
        "The service provider says it will not pay for indirect or consequential losses caused by the agreement.",
    },
  ],
};

export const languageOptionFallback = [
  { code: "english", label: "English" },
  { code: "hindi", label: "हिन्दी" },
  { code: "marathi", label: "मराठी" },
  { code: "gujarati", label: "ગુજરાતી" },
];

export const uiText = {
  english: {
    heroTitle: "Making legal documents readable, teachable, and verifiable.",
    heroLead:
      "Register, upload a legal document, extract clauses, simplify legal language, preview translations, flag risks, and ask an AI legal assistant for plain-language explanations.",
    reactFrontend: "React frontend",
    expressApi: "Express API",
    jwtAuth: "JWT auth",
    sqliteStorage: "SQLite storage",
    openaiAssistant: "OpenAI-ready assistant",
    stackTitle: "Project stack in place",
    stackItems: [
      "User registration and login",
      "Private saved-document library per user",
      "Clause analysis and verification records",
      "OpenAI-backed upgrade path for assistant responses",
    ],
    step1: "Analyze a legal document",
    loadDemo: "Load Demo Text",
    documentTitle: "Document title",
    pasteLegalText: "Paste legal text",
    analyzeText: "Analyze Text",
    uploadFile: "Upload File",
    uploadsHelp: "Supported uploads: TXT, MD, DOC, DOCX, and PDF.",
    library: "History",
    noDocs: "No saved documents yet. Analyze one to store it in your account.",
    insights: "Document insights",
    emptyInsights: "Run an analysis to see clause breakdowns, warnings, translations, and verification details.",
    activeDocument: "Active document",
    playInsights: "Play Insights",
    stopAudio: "Stop Audio",
    totalClauses: "Total clauses",
    highImportance: "High importance",
    riskFlags: "Risk flags",
    readTime: "Read time",
    verification: "Verification",
    fingerprint: "Fingerprint",
    reminders: "Frequent rule reminders",
    clauseExplorer: "Clause explorer",
    original: "Original",
    simplified: "Simplified",
    fullDocumentView: "Full document view",
    originalDocumentText: "Original document text",
    translatedNotAvailable: "Full document translation needs AI translation. The translated insights and audio above already follow the selected language.",
    assistant: "AI legal assistant",
    ask: "Ask",
    playAssistant: "Play Assistant",
    whyItMatters: "Why it matters:",
    whatYouCanDo: "What you can do next:",
    nextStep: "Next step:",
    authRequired: "Auth required",
    logout: "Logout",
  },
  hindi: {
    heroTitle: "कानूनी दस्तावेज़ों को पढ़ने, समझने और जाँचने योग्य बनाइए।",
    heroLead:
      "रजिस्टर करें, कानूनी दस्तावेज़ अपलोड करें, क्लॉज़ पहचानें, कानूनी भाषा को सरल बनाएं, अनुवाद देखें, जोखिम समझें, और AI कानूनी सहायक से आसान भाषा में मदद लें।",
    reactFrontend: "रिएक्ट फ्रंटएंड",
    expressApi: "एक्सप्रेस API",
    jwtAuth: "JWT ऑथ",
    sqliteStorage: "SQLite स्टोरेज",
    openaiAssistant: "OpenAI सहायक",
    stackTitle: "प्रोजेक्ट स्टैक तैयार है",
    stackItems: [
      "यूज़र रजिस्ट्रेशन और लॉगिन",
      "हर यूज़र के लिए निजी सेव डॉक्युमेंट लाइब्रेरी",
      "क्लॉज़ विश्लेषण और सत्यापन रिकॉर्ड",
      "सहायक उत्तरों के लिए OpenAI आधारित अपग्रेड",
    ],
    step1: "कानूनी दस्तावेज़ का विश्लेषण करें",
    loadDemo: "डेमो टेक्स्ट लोड करें",
    documentTitle: "दस्तावेज़ शीर्षक",
    pasteLegalText: "कानूनी टेक्स्ट पेस्ट करें",
    analyzeText: "विश्लेषण करें",
    uploadFile: "फ़ाइल अपलोड करें",
    uploadsHelp: "समर्थित फ़ाइलें: TXT, MD, DOC, DOCX और PDF।",
    library: "सेव किए गए दस्तावेज़",
    noDocs: "अभी कोई सेव दस्तावेज़ नहीं है। विश्लेषण करके इसे अपने खाते में सेव करें।",
    insights: "दस्तावेज़ की जानकारी",
    emptyInsights: "क्लॉज़, चेतावनी, अनुवाद और सत्यापन देखने के लिए विश्लेषण चलाएँ।",
    activeDocument: "सक्रिय दस्तावेज़",
    playInsights: "जानकारी सुनें",
    stopAudio: "ऑडियो रोकें",
    totalClauses: "कुल क्लॉज़",
    highImportance: "उच्च महत्व",
    riskFlags: "जोखिम संकेत",
    readTime: "पढ़ने का समय",
    verification: "सत्यापन",
    fingerprint: "फिंगरप्रिंट",
    reminders: "महत्वपूर्ण याद दिलाने वाली बातें",
    clauseExplorer: "क्लॉज़ विवरण",
    original: "मूल",
    simplified: "सरल रूप",
    fullDocumentView: "पूरा दस्तावेज़ दृश्य",
    originalDocumentText: "मूल दस्तावेज़ टेक्स्ट",
    translatedNotAvailable: "पूरा दस्तावेज़ अनुवाद AI translation के बिना उपलब्ध नहीं है। ऊपर की जानकारी और ऑडियो चुनी गई भाषा में उपलब्ध हैं।",
    assistant: "AI कानूनी सहायक",
    ask: "पूछें",
    playAssistant: "सहायक सुनें",
    whyItMatters: "यह क्यों महत्वपूर्ण है:",
    whatYouCanDo: "अब आप क्या कर सकते हैं:",
    nextStep: "अगला कदम:",
    authRequired: "लॉगिन आवश्यक है",
    logout: "लॉगआउट",
  },
  marathi: {
    heroTitle: "कायदेशीर दस्तावेज वाचण्यास, समजण्यास आणि पडताळण्यासाठी सोपे करा.",
    heroLead:
      "नोंदणी करा, कायदेशीर दस्तावेज अपलोड करा, क्लॉज ओळखा, कायदेशीर भाषा सोपी करा, भाषांतरे पहा, जोखीम समजा, आणि AI कायदेशीर सहाय्यकाकडून सोप्या भाषेत मदत घ्या.",
    reactFrontend: "रिऍक्ट फ्रंटएंड",
    expressApi: "एक्सप्रेस API",
    jwtAuth: "JWT ऑथ",
    sqliteStorage: "SQLite स्टोरेज",
    openaiAssistant: "OpenAI सहाय्यक",
    stackTitle: "प्रोजेक्ट स्टॅक तयार आहे",
    stackItems: [
      "युजर नोंदणी आणि लॉगिन",
      "प्रत्येक युजरसाठी खाजगी सेव्ह डॉक्युमेंट लायब्ररी",
      "क्लॉज विश्लेषण आणि पडताळणी नोंदी",
      "सहाय्यक उत्तरांसाठी OpenAI आधारित अपग्रेड",
    ],
    step1: "कायदेशीर दस्तावेजाचे विश्लेषण करा",
    loadDemo: "डेमो मजकूर लोड करा",
    documentTitle: "दस्तावेज शीर्षक",
    pasteLegalText: "कायदेशीर मजकूर पेस्ट करा",
    analyzeText: "विश्लेषण करा",
    uploadFile: "फाइल अपलोड करा",
    uploadsHelp: "समर्थित फाइल्स: TXT, MD, DOC, DOCX आणि PDF.",
    library: "सेव्ह केलेले दस्तावेज",
    noDocs: "अजून सेव्ह दस्तावेज नाहीत. विश्लेषण करून खात्यात जतन करा.",
    insights: "दस्तावेज माहिती",
    emptyInsights: "क्लॉज, चेतावणी, भाषांतर आणि पडताळणी पाहण्यासाठी विश्लेषण चालवा.",
    activeDocument: "सक्रिय दस्तावेज",
    playInsights: "माहिती ऐका",
    stopAudio: "ऑडिओ थांबवा",
    totalClauses: "एकूण क्लॉज",
    highImportance: "उच्च महत्त्व",
    riskFlags: "जोखीम संकेत",
    readTime: "वाचन वेळ",
    verification: "पडताळणी",
    fingerprint: "फिंगरप्रिंट",
    reminders: "महत्त्वाच्या आठवणी",
    clauseExplorer: "क्लॉज तपशील",
    original: "मूळ",
    simplified: "सोपे रूप",
    fullDocumentView: "पूर्ण दस्तावेज दृश्य",
    originalDocumentText: "मूळ दस्तावेज मजकूर",
    translatedNotAvailable: "पूर्ण दस्तावेजाचे भाषांतर AI translation शिवाय उपलब्ध नाही. वरची माहिती आणि ऑडिओ निवडलेल्या भाषेत आहेत.",
    assistant: "AI कायदेशीर सहाय्यक",
    ask: "विचारा",
    playAssistant: "सहाय्यक ऐका",
    whyItMatters: "हे का महत्त्वाचे आहे:",
    whatYouCanDo: "आता तुम्ही काय करू शकता:",
    nextStep: "पुढचे पाऊल:",
    authRequired: "लॉगिन आवश्यक आहे",
    logout: "लॉगआउट",
  },
  gujarati: {
    heroTitle: "કાનૂની દસ્તાવેજોને વાંચવા, સમજવા અને ચકાસવા યોગ્ય બનાવો.",
    heroLead:
      "રજીસ્ટર કરો, કાનૂની દસ્તાવેજ અપલોડ કરો, ક્લૉઝ ઓળખો, કાનૂની ભાષા સરળ બનાવો, અનુવાદ જુઓ, જોખમ સમજો અને AI કાનૂની સહાયક પાસેથી સરળ ભાષામાં મદદ લો.",
    reactFrontend: "રીએક્ટ ફ્રન્ટએન્ડ",
    expressApi: "એક્સપ્રેસ API",
    jwtAuth: "JWT ઓથ",
    sqliteStorage: "SQLite સ્ટોરેજ",
    openaiAssistant: "OpenAI સહાયક",
    stackTitle: "પ્રોજેક્ટ સ્ટેક તૈયાર છે",
    stackItems: [
      "યુઝર રજીસ્ટ્રેશન અને લૉગિન",
      "દરેક યુઝર માટે ખાનગી સેવ્ડ દસ્તાવેજ લાયબ્રેરી",
      "ક્લૉઝ વિશ્લેષણ અને ચકાસણી રેકોર્ડ્સ",
      "સહાયક જવાબો માટે OpenAI આધારિત અપગ્રેડ",
    ],
    step1: "કાનૂની દસ્તાવેજનું વિશ્લેષણ કરો",
    loadDemo: "ડેમો લખાણ લોડ કરો",
    documentTitle: "દસ્તાવેજ શીર્ષક",
    pasteLegalText: "કાનૂની લખાણ પેસ્ટ કરો",
    analyzeText: "વિશ્લેષણ કરો",
    uploadFile: "ફાઇલ અપલોડ કરો",
    uploadsHelp: "સમર્થિત ફાઇલો: TXT, MD, DOC, DOCX અને PDF.",
    library: "સેવ થયેલા દસ્તાવેજો",
    noDocs: "હજુ સુધી કોઈ સેવ થયેલો દસ્તાવેજ નથી. વિશ્લેષણ કરીને તેને તમારા ખાતામાં સેવ કરો.",
    insights: "દસ્તાવેજ જાણકારી",
    emptyInsights: "ક્લૉઝ, ચેતવણીઓ, અનુવાદ અને ચકાસણી જોવા વિશ્લેષણ ચલાવો.",
    activeDocument: "સક્રિય દસ્તાવેજ",
    playInsights: "જાણકારી સાંભળો",
    stopAudio: "ઓડિયો રોકો",
    totalClauses: "કુલ ક્લૉઝ",
    highImportance: "ઉચ્ચ મહત્ત્વ",
    riskFlags: "જોખમ સંકેતો",
    readTime: "વાંચવાનો સમય",
    verification: "ચકાસણી",
    fingerprint: "ફિંગરપ્રિન્ટ",
    reminders: "મહત્વપૂર્ણ યાદ અપાવનાર મુદ્દાઓ",
    clauseExplorer: "ક્લૉઝ વિગત",
    original: "મૂળ",
    simplified: "સરળ રૂપ",
    fullDocumentView: "પૂર્ણ દસ્તાવેજ દૃશ્ય",
    originalDocumentText: "મૂળ દસ્તાવેજ લખાણ",
    translatedNotAvailable: "પૂર્ણ દસ્તાવેજ ભાષાંતર AI translation વગર ઉપલબ્ધ નથી. ઉપરની જાણકારી અને ઓડિયો પસંદ કરેલી ભાષામાં ઉપલબ્ધ છે.",
    assistant: "AI કાનૂની સહાયક",
    ask: "પૂછો",
    playAssistant: "સહાયક સાંભળો",
    whyItMatters: "આ કેમ મહત્વનું છે:",
    whatYouCanDo: "હવે તમે શું કરી શકો:",
    nextStep: "આગળનું પગલું:",
    authRequired: "લૉગિન જરૂરી છે",
    logout: "લૉગઆઉટ",
  },
};

export const localTermMaps = {
  hindi: {
    Payment: "भुगतान",
    Termination: "समाप्ति",
    Confidentiality: "गोपनीयता",
    Liability: "दायित्व",
    Compliance: "अनुपालन",
    Obligation: "जिम्मेदारी",
    General: "सामान्य",
    High: "उच्च",
    Medium: "मध्यम",
    Low: "कम",
    importance: "महत्व",
    "Key terms": "मुख्य शब्द",
    Confidence: "विश्वास",
    "AI confidence": "एआई विश्वास",
    Simplify: "सरलीकरण",
    Suggestions: "सुझाव",
    Risk: "जोखिम",
    "User helpfulness": "उपयोगकर्ता उपयोगिता",
    "Thanks for your feedback!": "आपकी प्रतिक्रिया के लिए धन्यवाद!",
    "Was this helpful?": "क्या यह उपयोगी था?",
  },
  marathi: {
    Payment: "भरणा",
    Termination: "समाप्ती",
    Confidentiality: "गोपनीयता",
    Liability: "दायित्व",
    Compliance: "अनुपालन",
    Obligation: "जबाबदारी",
    General: "सामान्य",
    High: "उच्च",
    Medium: "मध्यम",
    Low: "कमी",
    importance: "महत्त्व",
    "Key terms": "मुख्य शब्द",
    Confidence: "विश्वास",
    "AI confidence": "एआय विश्वास",
    Simplify: "सुलभीकरण",
    Suggestions: "सूचना",
    Risk: "जोखीम",
    "User helpfulness": "वापरकर्ता उपयुक्तता",
    "Thanks for your feedback!": "तुमच्या अभिप्रायाबद्दल धन्यवाद!",
    "Was this helpful?": "हे उपयोगी होते का?",
  },
  gujarati: {
    Payment: "ચુકવણી",
    Termination: "સમાપ્તિ",
    Confidentiality: "ગોપનીયતા",
    Liability: "જવાબદારી",
    Compliance: "અનુપાલન",
    Obligation: "જવાબદારી",
    General: "સામાન્ય",
    High: "ઉચ્ચ",
    Medium: "મધ્યમ",
    Low: "ઓછું",
    importance: "મહત્વ",
    "Key terms": "મુખ્ય શબ્દો",
    Confidence: "વિશ્વાસ",
    "AI confidence": "એઆઈ વિશ્વાસ",
    Simplify: "સરળીકરણ",
    Suggestions: "સૂચનો",
    Risk: "જોખમ",
    "User helpfulness": "વપરાશકર્તા ઉપયોગિતા",
    "Thanks for your feedback!": "તમારા પ્રતિસાદ માટે આભાર!",
    "Was this helpful?": "શું આ ઉપયોગી હતું?",
  },
};
